version: '3'

services:
#  jaeger:
#    image: jaegertracing/all-in-one:1.46
#    ports:
#      - "6831:6831/udp"
#      - "16686:16686"
  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.46
    ports:
      - "6831:6831/udp"
    environment:
      SPAN_STORAGE_TYPE: memory
    command:
      - "--reporter.grpc.host-port=jaeger-collector:14250"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.46
    command:
      - "--grpc-storage.server=jaeger-remote-storage:17271"
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin

  jaeger-query:
    image: jaegertracing/jaeger-query:1.46
    ports:
      - "16686:16686"
    environment:
      SPAN_STORAGE_TYPE: memory

  jaeger-remote-storage:
    image: jaegertracing/jaeger-remote-storage:1.46
    ports:
      - "17271:17271"
    environment:
      SPAN_STORAGE_TYPE: memory

  app:
    image: opentracing-demo-app
